version: "3"
services:
  db:
    image: mysql:8.0.32
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: technical_test
      MYSQL_USER: factorial
      MYSQL_PASSWORD: Password123#..
    ports:
      - 3306:3306

  app:
    build: ./app
    ports:
      - 80:5000
    depends_on:
      - db
    command: sh -c "sleep 60s ; python3 ./app.py"

